### ISSUE TITLE
Job Allocation and Assembly Error

### ISSUE THREAD

**Issue by IsaiahKelly** [Unity-Technologies/ai-planner-samples#1]
I get these error messages when I load EscapeRoom project in Unity 2019.3.0f3 and enter play mode with scene FirstRoom. I have correctly cloned the project to my local machine using git.

![unity_JobTempAlloc](https://user-images.githubusercontent.com/7953130/71526262-0ad99280-28a4-11ea-85a2-6b6a2b73c3f4.png)

Executing menu command AI > Planner > Generate assemblies and entering play mode again forces an exit from play mode and gives these error messages.

![unity_assembly_error](https://user-images.githubusercontent.com/7953130/71526926-ffd43180-28a6-11ea-8435-b9bb20aa8187.png)

![unity_assembly_error2](https://user-images.githubusercontent.com/7953130/71526928-02cf2200-28a7-11ea-858b-23362409cd76.png)

Entering play mode a third time will repeat the JobTempAlloc error messages from the first run.

I tested these steps with both Visual Studio Code and Visual Studio Community 2017 set as default editor just in case that was connected to the problem.

I can see there is generated code listed in the package manager. Is this correct?

![unity_pacman_generated](https://user-images.githubusercontent.com/7953130/71526970-3316c080-28a7-11ea-9f2c-204333b7a4f4.png)

**Comment by IsaiahKelly** [comment]
I've tested the other example projects now and the VacuumRobot scenes are the only ones to run without JobTempAlloc errors at the moment.

**Comment by amirebrahimi** [comment]
This will be fixed in the next release. Thank you for reporting it.

**Comment by IsaiahKelly** [comment]
Just came back to test the latest samples but unfortunately I'm still getting these errors on Windows 10 and Unity 2019.3.7f1

I tried closing and reopening the project but now generating assembles fails? (menu option doesn't become disabled). I feel like there must be some critical setup step for dependencies I'm missing. So maybe a more detailed Installation/troubleshooting guide (or link to one) in the readme would be helpful.

**Comment by amirebrahimi** [comment]
We haven't released our next version, so the original error about JobTempAlloc will still occur. However, for re-generating your assemblies you could try deleting the generated packages under your Packages directory and then regenerate the assemblies via the AI top-level menu.

**Comment by IsaiahKelly** [comment]
Thanks for the clarification. So by "next version" I assume you mean 0.3.x or above?

**Comment by amirebrahimi** [comment]
Yes
