### ISSUE TITLE
Can't clone with LFS files

### ISSUE THREAD

**Issue by revanaii** [Unity-Technologies/ai-planner-samples#2]
I see the LFS pointers in .git, but the actual files don't get pulled. Tried `git lfs fetch` `git lfs pull` with no luck. Are the pointers still correct?
Any suggestion will be appreciated.

**Comment by amirebrahimi** [comment]
I just tried cloning and had no problem:
![image](https://user-images.githubusercontent.com/904110/75063052-e6abc380-5498-11ea-824c-a323fe9d98b4.png)

Can you double check your git and git-lfs versions? Also, you shouldn't have to manually lfs pull with the latest version of git.

**Comment by revanaii** [comment]
I updated both git and git-lfs - problem solved. Thanks for the quick reply!
